services:
  gymmaster_ag:
    container_name: gymmaster_ag
    build: .
    env_file:
      - .env.docker
    ports:
      - '4000:4000'
    networks:
      - shared_network
    depends_on:
      - machine_service
      - progress_service
  machine_service:
    container_name: machine-service
    image: davara13/machine-service:latest
    env_file:
      - .env.docker
    restart: always
    ports:
      - '8082:8082'
    networks:
      - shared_network
  progress_service:
    container_name: progress-service
    image: dfbello/progress_tracking:latest
    env_file:
      - .env.docker
    restart: always
    ports:
      - '8080:8080' 
    networks:
      - shared_network
networks:
  shared_network:
    external: true
