services:
  gymmaster_ag:
    container_name: gymmaster_ag
    build: .
    env_file:
      - .env.docker
    ports:
      - "4000:4000"
    networks:
      - shared_network

  auth_ms:
    container_name: auth_ms
    image: dbellol/auth_ms-app:latest  
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env.docker
    networks:
      - shared_network

  machine_service:
    container_name: machine_service
    image: davara13/machine-service:latest
    restart: always
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    networks:
      - shared_network

  routine_service:
    container_name: routine_service
    build:
      context: ./routines_ms
    env_file:
      - .env.docker
    image: halfonsoh/routines-service:latest
    ports:
      - "3001:3001"
    networks:
      - shared_network

  monitoring_service:
    container_name: monitoring_service
    image: aldiazve/archi-monitoring:latest
    restart: always
    env_file:
      - .env.docker
    ports:
      - "3002:3000"
    networks:
      - shared_network

networks:
  shared_network:
    external: true

