services:
  gymmaster_ag:
    container_name: gymmaster_ag
    build: .
    env_file:
      - .env.docker
    ports:
      - '4000:4000'
    networks:
      - shared_network
    depends_on:
      - progress_tracking

  progress_tracking:
    container_name: progress_tracking
    image: dfbello/progress_tracking:latest
    restart: always
    ports:
      - '8082:8080'
    networks:
      - shared_network

networks:
  shared_network:
    external: true
