version: '3.8'

services:
  gymmaster_ag:
    container_name: gymmaster_ag
    build: .
    env_file:
      - .env.docker
    ports:
      - '4000:4000'
    networks:
      - shared_network
    depends_on:
      - machine_service

machine_service:
    container_name: machine_service
    image: davara13/machine-service:latest
    restart: always
    ports:
      - '8080:8080'
    networks:
      - shared_network

networks:
  shared_network:
    external: true
